version: "3.9"
services:
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.14
    restart: always
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

volumes:
  config:
  data:
  log:

