# Application Properties
application:
  jwt:
    # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
    #  for production: - In the `SECURITY_AUTHENTICATION_JWT_BASE64_SECRET` environment variable
    base64-secret: NjlhYjJhOWNkMDYwM2ZiZTk1MWQ0YmZkNmYzYjc2MGJiZjAwMWZkMzdiZTIyNjBhMzE2MzU2MzU4ZjhkYTY3YWVkNjU1ZDQyZjcwM2IzNmJhNzZiOWU3ODdhZDcwOTFjMmM4OTU0ZmU2ZWQ4YWNmZmRiZDRhMGE3ZTQzY2YyZGM=
    token-validity-in-seconds: 86400 # Token is valid 24 hours
    token-validity-in-seconds-for-remember-me: 2592000 # Token is valid 30 days

  mail:
    from: iotCore@localhost
    base-url: http://127.0.0.1:8080 # Modify according to your server's URL

  ehcache:
    time-to-live-seconds: 3600 # 1 hour
    max-entries: 100

  clientApp:
    name: 'IOT Core'

# Actuator
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - env
          - configprops
          - health
          - logfile
          - info
          - loggers
          - threaddump
          - caches
          - scheduledtasks
          - liquibase
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
      roles:
        - ROLE_ADMIN

# Open Api
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
  show-actuator: true
  writer-with-default-pretty-printer: true

# Spring related properties
spring:
  messages:
    basename: i18n/messages

# Server properties
server:
  port: 8080