version: '3.8'
services:
  t_iot-mysql:
    image: mysql:8.0.28
    volumes:
      - ~/volumes/t_iot/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=t_iot
    ports:
      - "3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

volumes:
  mysql_data:
