name: IOT Core CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build Data Layer
        run: mvn -B install --file iot-core-data/pom.xml
      - name: Build Business Layer
        run: mvn -B install --file iot-core-business/pom.xml
      - name: Build Web Layer
        run: mvn -B install --file iot-core-web/pom.xml
      - name: Build Mqtt Client
        run: mvn -B install --file mqtt-client/pom.xml
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
      - name: send to codecov
        run: bash <(curl -s https://codecov.io/bash)